global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FileWallBall 애플리케이션 메트릭
  - job_name: 'filewallball-api'
    static_configs:
      - targets: ['filewallball:8000']
    metrics_path: /metrics
    scheme: http

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    scheme: http 