---
# fileWallBall 네임스페이스
apiVersion: v1
kind: Namespace
metadata:
  name: filewallball
  labels:
    name: filewallball
    app: filewallball
    environment: production
---
# ResourceQuota - 네임스페이스 리소스 제한
apiVersion: v1
kind: ResourceQuota
metadata:
  name: filewallball-quota
  namespace: filewallball
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    services: "10"
    services.loadbalancers: "2"
    services.nodeports: "5"
    count/pods: "20"
    count/deployments.apps: "5"
    count/statefulsets.apps: "2"
    count/jobs.batch: "5"
---
# LimitRange - 컨테이너별 기본 리소스 제한
apiVersion: v1
kind: LimitRange
metadata:
  name: filewallball-limits
  namespace: filewallball
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - max:
      cpu: 1000m
      memory: 1Gi
    min:
      cpu: 200m
      memory: 256Mi
    type: Pod
---
# ServiceAccount - 애플리케이션용 서비스 계정
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filewallball-sa
  namespace: filewallball
  labels:
    app: filewallball
---
# Role - 네임스페이스 내 권한 정의
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filewallball-role
  namespace: filewallball
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# RoleBinding - ServiceAccount와 Role 연결
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filewallball-rolebinding
  namespace: filewallball
subjects:
- kind: ServiceAccount
  name: filewallball-sa
  namespace: filewallball
roleRef:
  kind: Role
  name: filewallball-role
  apiGroup: rbac.authorization.k8s.io
---
# NetworkPolicy - 네임스페이스 내부 통신 정책
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: filewallball-network-policy
  namespace: filewallball
spec:
  podSelector:
    matchLabels:
      app: filewallball
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: filewallball
    ports:
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
