---
# ConfigMap - 애플리케이션 환경 설정
apiVersion: v1
kind: ConfigMap
metadata:
  name: filewallball-app-config
  namespace: filewallball
  labels:
    app: filewallball
    component: config
data:
  # 데이터베이스 설정
  DATABASE_HOST: "mariadb-service"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "filewallball"

  # Redis 설정
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  # 애플리케이션 설정
  LOG_LEVEL: "INFO"
  WORKERS: "1"
  TIMEOUT: "30"
  MAX_CONNECTIONS: "100"

  # 파일 업로드 설정 - 기본
  MAX_FILE_SIZE: "104857600"
  ALLOWED_EXTENSIONS: '["jpg","jpeg","png","gif","pdf","doc","docx","txt","zip","rar"]'
  UPLOAD_PATH: "/app/uploads"

  # 파일 업로드 설정 - 고급 경로 매핑
  HOST_UPLOAD_DIR: "/mnt/filewallball/uploads"
  CONTAINER_UPLOAD_DIR: "/app/uploads"
  STORAGE_TYPE: "local"
  LOCAL_STORAGE_PATH: "/app/uploads"
  STORAGE_STRUCTURE: "date"
  STORAGE_DATE_FORMAT: "%Y/%m/%d"
  STORAGE_UUID_DEPTH: "2"

  # S3 Storage 설정 (선택적)
  S3_BUCKET: ""
  S3_REGION: "us-east-1"
  S3_ENDPOINT_URL: "https://s3.amazonaws.com"

  # Azure Blob Storage 설정 (선택적)
  AZURE_CONNECTION_STRING: ""
  AZURE_CONTAINER_NAME: ""

  # Google Cloud Storage 설정 (선택적)
  GCS_BUCKET: ""
  GCS_CREDENTIALS_FILE: ""

  # 보안 설정
  CORS_ORIGINS: '["*"]'
  RATE_LIMIT_PER_MINUTE: "100"

  # 메트릭 설정
  METRICS_ENABLED: "true"
  METRICS_PORT: "8000"
---
# Secret - 민감 정보
apiVersion: v1
kind: Secret
metadata:
  name: filewallball-app-secret
  namespace: filewallball
  labels:
    app: filewallball
    component: secret
type: Opaque
data:
  # 데이터베이스 비밀번호 (base64 인코딩)
  DATABASE_PASSWORD: "ZmlsZXdhbGxiYWxsMjAyNA=="  # filewallball2024

  # JWT 시크릿 키 (base64 인코딩)
  JWT_SECRET_KEY: "ZmlsZXdhbGxiYWxsLWp3dC1zZWNyZXQta2V5LTIwMjQ="  # filewallball-jwt-secret-key-2024

  # Redis 비밀번호 (base64 인코딩)
  REDIS_PASSWORD: "ZmlsZXdhbGxiYWxsMjAyNA=="  # filewallball2024

  # API 키 (base64 인코딩)
  API_SECRET_KEY: "ZmlsZXdhbGxiYWxsLWFwaS1zZWNyZXQta2V5LTIwMjQ="  # filewallball-api-secret-key-2024

  # S3 인증 정보 (base64 인코딩, 선택적)
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""

  # Azure 인증 정보 (base64 인코딩, 선택적)
  AZURE_CONNECTION_STRING: ""

  # GCS 인증 정보 (base64 인코딩, 선택적)
  GCS_CREDENTIALS: ""
---
# ConfigMap - 환경별 설정 (Production)
apiVersion: v1
kind: ConfigMap
metadata:
  name: filewallball-prod-config
  namespace: filewallball
  labels:
    app: filewallball
    environment: production
    component: config
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "WARNING"
  WORKERS: "2"
  TIMEOUT: "60"
  MAX_CONNECTIONS: "200"
  RATE_LIMIT_PER_MINUTE: "50"
  # 프로덕션 파일 저장소 설정
  STORAGE_TYPE: "local"
  STORAGE_STRUCTURE: "date"
  HOST_UPLOAD_DIR: "/mnt/filewallball/prod/uploads"
  CONTAINER_UPLOAD_DIR: "/app/uploads"
---
# ConfigMap - 환경별 설정 (Development)
apiVersion: v1
kind: ConfigMap
metadata:
  name: filewallball-dev-config
  namespace: filewallball
  labels:
    app: filewallball
    environment: development
    component: config
data:
  ENVIRONMENT: "development"
  DEBUG: "true"
  LOG_LEVEL: "DEBUG"
  WORKERS: "1"
  TIMEOUT: "30"
  MAX_CONNECTIONS: "50"
  RATE_LIMIT_PER_MINUTE: "1000"
  # 개발 파일 저장소 설정
  STORAGE_TYPE: "local"
  STORAGE_STRUCTURE: "uuid"
  HOST_UPLOAD_DIR: "/mnt/filewallball/dev/uploads"
  CONTAINER_UPLOAD_DIR: "/app/uploads"
