apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filewallball-pvc
  namespace: filewallball
  labels:
    app: filewallball
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi