---
# Deployment - FastAPI 애플리케이션
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filewallball-deployment
  namespace: filewallball
  labels:
    app: filewallball
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filewallball
      component: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: filewallball
        component: api
    spec:
      serviceAccountName: filewallball-sa
      containers:
      - name: filewallball
        image: filewallball:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        # ConfigMap에서 환경 변수 주입
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: DATABASE_NAME
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: REDIS_PORT
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: REDIS_DB
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: LOG_LEVEL
        - name: WORKERS
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: WORKERS
        - name: TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: TIMEOUT
        - name: MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: MAX_CONNECTIONS
        - name: MAX_FILE_SIZE
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: MAX_FILE_SIZE
        - name: ALLOWED_EXTENSIONS
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: ALLOWED_EXTENSIONS
        - name: UPLOAD_PATH
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: UPLOAD_PATH
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: CORS_ORIGINS
        - name: RATE_LIMIT_PER_MINUTE
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: RATE_LIMIT_PER_MINUTE
        - name: METRICS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: METRICS_ENABLED
        - name: METRICS_PORT
          valueFrom:
            configMapKeyRef:
              name: filewallball-app-config
              key: METRICS_PORT
        # Secret에서 민감 정보 주입
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: filewallball-app-secret
              key: DATABASE_PASSWORD
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: filewallball-app-secret
              key: JWT_SECRET_KEY
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: filewallball-app-secret
              key: REDIS_PASSWORD
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: filewallball-app-secret
              key: API_SECRET_KEY
        # 환경 변수 추가
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 30
          failureThreshold: 5
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
          subPath: files
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: filewallball-pvc
---
# Service - ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: filewallball-service
  namespace: filewallball
  labels:
    app: filewallball
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: filewallball
    component: api
---
# Service - LoadBalancer (외부 접근용)
apiVersion: v1
kind: Service
metadata:
  name: filewallball-loadbalancer
  namespace: filewallball
  labels:
    app: filewallball
    component: api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: filewallball
    component: api
