apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb-rolebinding
  namespace: filewallball
subjects:
- kind: ServiceAccount
  name: mariadb
  namespace: filewallball
roleRef:
  kind: Role
  name: mariadb-role
  apiGroup: rbac.authorization.k8s.io
