apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-script
  namespace: filewallball
data:
  init.sql: |
    -- FileWallBall Database Schema
    -- MariaDB 10.11

    USE filewallball;

    -- 파일 정보 테이블
    CREATE TABLE files (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        filename VARCHAR(255) NOT NULL COMMENT '저장된 파일명',
        original_filename VARCHAR(255) NOT NULL COMMENT '원본 파일명',
        file_size BIGINT NOT NULL COMMENT '파일 크기 (bytes)',
        mime_type VARCHAR(100) NOT NULL COMMENT 'MIME 타입',
        upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '업로드 날짜',
        is_deleted BOOLEAN DEFAULT FALSE COMMENT '삭제 여부',
        deleted_date TIMESTAMP NULL COMMENT '삭제 날짜',
        category_id INT NULL COMMENT '카테고리 ID',
        description TEXT NULL COMMENT '파일 설명',
        checksum VARCHAR(64) NULL COMMENT '파일 체크섬 (SHA256)',
        INDEX idx_upload_date (upload_date),
        INDEX idx_is_deleted (is_deleted),
        INDEX idx_category_id (category_id),
        INDEX idx_filename (filename)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- 파일 카테고리 테이블
    CREATE TABLE file_categories (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL COMMENT '카테고리명',
        description TEXT NULL COMMENT '카테고리 설명',
        created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 날짜',
        is_active BOOLEAN DEFAULT TRUE COMMENT '활성화 여부',
        UNIQUE KEY uk_category_name (name),
        INDEX idx_is_active (is_active)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- 파일 조회 기록 테이블
    CREATE TABLE file_views (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        file_id BIGINT NOT NULL COMMENT '파일 ID',
        view_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '조회 날짜',
        ip_address VARCHAR(45) NULL COMMENT 'IP 주소',
        user_agent TEXT NULL COMMENT '사용자 에이전트',
        session_id VARCHAR(255) NULL COMMENT '세션 ID',
        INDEX idx_file_id (file_id),
        INDEX idx_view_date (view_date),
        INDEX idx_ip_address (ip_address),
        FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- 파일 다운로드 기록 테이블
    CREATE TABLE file_downloads (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        file_id BIGINT NOT NULL COMMENT '파일 ID',
        download_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '다운로드 날짜',
        ip_address VARCHAR(45) NULL COMMENT 'IP 주소',
        user_agent TEXT NULL COMMENT '사용자 에이전트',
        session_id VARCHAR(255) NULL COMMENT '세션 ID',
        download_size BIGINT NULL COMMENT '다운로드된 크기',
        INDEX idx_file_id (file_id),
        INDEX idx_download_date (download_date),
        INDEX idx_ip_address (ip_address),
        FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- 파일 공유 링크 테이블
    CREATE TABLE file_shares (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        file_id BIGINT NOT NULL COMMENT '파일 ID',
        share_token VARCHAR(64) NOT NULL COMMENT '공유 토큰',
        created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 날짜',
        expires_date TIMESTAMP NULL COMMENT '만료 날짜',
        max_downloads INT NULL COMMENT '최대 다운로드 수',
        current_downloads INT DEFAULT 0 COMMENT '현재 다운로드 수',
        is_active BOOLEAN DEFAULT TRUE COMMENT '활성화 여부',
        UNIQUE KEY uk_share_token (share_token),
        INDEX idx_file_id (file_id),
        INDEX idx_expires_date (expires_date),
        INDEX idx_is_active (is_active),
        FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- 기본 카테고리 데이터 삽입
    INSERT INTO file_categories (name, description) VALUES
    ('문서', 'PDF, Word, Excel 등 문서 파일'),
    ('이미지', 'JPG, PNG, GIF 등 이미지 파일'),
    ('동영상', 'MP4, AVI, MOV 등 동영상 파일'),
    ('음악', 'MP3, WAV, FLAC 등 음악 파일'),
    ('압축파일', 'ZIP, RAR, 7Z 등 압축 파일'),
    ('기타', '기타 파일들');

    -- 외래 키 제약 조건 추가
    ALTER TABLE files
    ADD CONSTRAINT fk_files_category
    FOREIGN KEY (category_id) REFERENCES file_categories(id) ON DELETE SET NULL;
