apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: filewallball
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: redis-exporter
  ports:
  - port: 9121
    targetPort: 9121
    name: metrics
  type: ClusterIP
