apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: filewallball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        ports:
        - containerPort: 9121
        env:
        - name: REDIS_ADDR
          value: "redis://redis-master:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: filewallball
spec:
  selector:
    app: redis-exporter
  ports:
  - port: 9121
    targetPort: 9121
    protocol: TCP
    name: http
  type: ClusterIP
