apiVersion: v1
kind: Pod
metadata:
  name: test-volume-pod
  namespace: filewallball
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: test-volume
      mountPath: /data
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: filewallball-storage-pvc
