apiVersion: v1
kind: ConfigMap
metadata:
  name: health-check-config
  namespace: filewallball
  labels:
    app: filewallball
data:
  # 헬스체크 설정
  health_check_config.yaml: |
    # 헬스체크 설정
    health_check:
      # 기본 헬스체크 설정
      basic:
        enabled: true
        endpoint: "/health"
        timeout: 5

      # 상세 헬스체크 설정
      detailed:
        enabled: true
        endpoint: "/health/detailed"
        timeout: 10

      # Liveness 프로브 설정
      liveness:
        enabled: true
        endpoint: "/health/live"
        initial_delay: 30
        period: 10
        timeout: 5
        failure_threshold: 3
        success_threshold: 1

      # Readiness 프로브 설정
      readiness:
        enabled: true
        endpoint: "/health/ready"
        initial_delay: 10
        period: 5
        timeout: 3
        failure_threshold: 3
        success_threshold: 1

      # 서비스 정보 설정
      info:
        enabled: true
        endpoint: "/info"
        timeout: 5
