apiVersion: apps/v1
kind: Deployment
metadata:
  name: filewallball-deployment
  namespace: filewallball
  labels:
    app: filewallball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filewallball
  template:
    metadata:
      labels:
        app: filewallball
    spec:
      containers:
      - name: filewallball
        image: filewallball-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "mariadb-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "filewallball_db"
        - name: DB_USER
          value: "filewallball_user"
        - name: DB_PASSWORD
          value: "filewallball_user_pass"
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "filewallball2024"
        - name: DEBUG
          value: "true"
        - name: LOG_LEVEL
          value: "DEBUG"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: filewallball-pvc 