apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filewallball-backup-pvc
  namespace: filewallball
  labels:
    app: filewallball-backup
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 