---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filewallball-backup-sa
  namespace: filewallball
  labels:
    app: filewallball-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filewallball-backup-role
  namespace: filewallball
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filewallball-backup-rolebinding
  namespace: filewallball
subjects:
- kind: ServiceAccount
  name: filewallball-backup-sa
  namespace: filewallball
roleRef:
  kind: Role
  name: filewallball-backup-role
  apiGroup: rbac.authorization.k8s.io 