apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filewallball-ingress
  namespace: filewallball
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: filewallball.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: filewallball-service
            port:
              number: 8000 