apiVersion: v1
kind: ConfigMap
metadata:
  name: filewallball-log-rotation
  namespace: filewallball
data:
  logrotate.conf: |
    /var/log/filewallball/*.log {
      daily
      rotate 7
      compress
      delaycompress
      missingok
      notifempty
      create 644 root root
      postrotate
        /bin/kill -HUP `cat /var/run/syslogd.pid 2>/dev/null` 2>/dev/null || true
      endscript
    } 