apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: filewallball
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP 