apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filewallball-pvc
  namespace: filewallball
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath 