---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: filewallball
  labels:
    app: redis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-role
  namespace: filewallball
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-rolebinding
  namespace: filewallball
subjects:
- kind: ServiceAccount
  name: redis
  namespace: filewallball
roleRef:
  kind: Role
  name: redis-role
  apiGroup: rbac.authorization.k8s.io 