apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: filewallball
  labels:
    app: redis
type: Opaque
data:
  # Redis 기본 비밀번호 (base64 encoded)
  redis-password: ZmlsZXdhbGxiYWxsMjAyNA== # base64 encoded "filewallball2024" 