apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: filewallball
  labels:
    app: redis
data:
  redis.conf: |
    # Redis 기본 설정
    bind 0.0.0.0
    port 6379
    timeout 0
    tcp-keepalive 300
    
    # 메모리 관리
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # 로깅 설정
    loglevel notice
    logfile ""
    
    # 데이터베이스 설정
    databases 16
    
    # 보안 설정
    requirepass filewallball2024
    
    # 성능 최적화
    tcp-backlog 511
    unixsocket /tmp/redis.sock
    unixsocketperm 700
    
    # 클라이언트 연결 설정
    maxclients 10000
    
    # 메모리 최적화
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    
    # AOF 설정 (선택적)
    appendonly no
    
    # RDB 스냅샷 설정
    save 900 1
    save 300 10
    save 60 10000
    
    # 복제 설정
    repl-diskless-sync no
    repl-diskless-sync-delay 5
    repl-ping-slave-period 10
    repl-timeout 60
    repl-disable-tcp-nodelay no
    repl-backlog-size 1mb
    repl-backlog-ttl 3600
    
    # 느린 쿼리 로그
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    
    # 지연 모니터링
    latency-monitor-threshold 0 