# Redis Master Service
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: filewallball
spec:
  selector:
    app: redis-master
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP
---
# Redis Slave Service
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: filewallball
spec:
  selector:
    app: redis-slave
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP
---
# Redis Sentinel Service
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: filewallball
spec:
  selector:
    app: redis-sentinel
  ports:
  - port: 26379
    targetPort: 26379
    name: sentinel
  type: ClusterIP
---
# Redis Service (for application access)
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: filewallball
spec:
  selector:
    app: redis-master
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP 