apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-rolebinding
  namespace: filewallball
subjects:
- kind: ServiceAccount
  name: redis
  namespace: filewallball
roleRef:
  kind: Role
  name: redis-role
  apiGroup: rbac.authorization.k8s.io 