apiVersion: v1
kind: ResourceQuota
metadata:
  name: filewallball-quota
  namespace: filewallball
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "5"
    services: "10"
    services.loadbalancers: "2"
    pods: "20"
    configmaps: "10"
    secrets: "10" 