apiVersion: v1
kind: Service
metadata:
  name: filewallball-api
  namespace: filewallball
  labels:
    app: filewallball
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: filewallball
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: filewallball-ingress
  namespace: filewallball
spec:
  selector:
    app: filewallball
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer 