apiVersion: v1
kind: Service
metadata:
  name: filewallball-service
  namespace: filewallball
spec:
  selector:
    app: filewallball
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: filewallball-ingress
  namespace: filewallball
spec:
  selector:
    app: filewallball
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer 