apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: filewallball
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m" 