"""Initial migration for FileWallBall models

Revision ID: 001
Revises: 
Create Date: 2025-07-28 01:42:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 파일 카테고리 테이블
    op.create_table('file_categories',
        sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    # 파일 확장자 테이블
    op.create_table('file_extensions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('extension', sa.String(length=10), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('is_allowed', sa.Boolean(), nullable=True),
        sa.Column('max_file_size', sa.BigInteger(), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('extension')
    )
    op.create_index(op.f('ix_file_extensions_extension'), 'file_extensions', ['extension'], unique=False)
    
    # 파일 태그 테이블
    op.create_table('file_tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tag_name', sa.String(length=50), nullable=False),
        sa.Column('tag_color', sa.String(length=7), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tag_name')
    )
    op.create_index(op.f('ix_file_tags_tag_name'), 'file_tags', ['tag_name'], unique=False)
    
    # 파일 정보 테이블
    op.create_table('files',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('file_uuid', sa.String(length=36), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('stored_filename', sa.String(length=255), nullable=False),
        sa.Column('file_extension', sa.String(length=20), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('file_size', sa.BigInteger(), nullable=False),
        sa.Column('file_hash', sa.String(length=64), nullable=True),
        sa.Column('storage_path', sa.String(length=500), nullable=False),
        sa.Column('file_category_id', sa.SmallInteger(), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['file_category_id'], ['file_categories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_uuid')
    )
    op.create_index(op.f('ix_files_created_at'), 'files', ['created_at'], unique=False)
    op.create_index(op.f('ix_files_file_extension'), 'files', ['file_extension'], unique=False)
    op.create_index(op.f('ix_files_file_hash'), 'files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_files_file_uuid'), 'files', ['file_uuid'], unique=False)
    op.create_index(op.f('ix_files_is_deleted'), 'files', ['is_deleted'], unique=False)
    
    # 파일 업로드 테이블
    op.create_table('file_uploads',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('file_id', sa.BigInteger(), nullable=False),
        sa.Column('upload_session_id', sa.String(length=36), nullable=True),
        sa.Column('client_ip', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('upload_status', sa.String(length=20), nullable=True),
        sa.Column('upload_started_at', sa.DateTime(), nullable=True),
        sa.Column('upload_completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_uploads_upload_session_id'), 'file_uploads', ['upload_session_id'], unique=False)
    
    # 파일-태그 관계 테이블
    op.create_table('file_tag_relations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('file_id', sa.BigInteger(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['file_tags.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id', 'tag_id')
    )
    
    # 파일 조회 로그 테이블
    op.create_table('file_views',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('file_id', sa.BigInteger(), nullable=False),
        sa.Column('viewer_ip', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('referer', sa.String(length=500), nullable=True),
        sa.Column('view_type', sa.Enum('info', 'preview', 'download'), nullable=False),
        sa.Column('session_id', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 파일 다운로드 로그 테이블
    op.create_table('file_downloads',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('file_id', sa.BigInteger(), nullable=False),
        sa.Column('downloader_ip', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('download_method', sa.Enum('direct', 'api', 'web'), nullable=False),
        sa.Column('bytes_downloaded', sa.BigInteger(), nullable=True),
        sa.Column('download_duration_ms', sa.Integer(), nullable=True),
        sa.Column('session_id', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 시스템 설정 테이블
    op.create_table('system_settings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('setting_key', sa.String(length=100), nullable=False),
        sa.Column('setting_value', sa.Text(), nullable=True),
        sa.Column('setting_type', sa.String(length=20), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('setting_key')
    )
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 시스템 설정 테이블 삭제
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_table('system_settings')
    
    # 파일 다운로드 로그 테이블 삭제
    op.drop_table('file_downloads')
    
    # 파일 조회 로그 테이블 삭제
    op.drop_table('file_views')
    
    # 파일-태그 관계 테이블 삭제
    op.drop_table('file_tag_relations')
    
    # 파일 업로드 테이블 삭제
    op.drop_table('file_uploads')
    
    # 파일 정보 테이블 삭제
    op.drop_index(op.f('ix_files_is_deleted'), table_name='files')
    op.drop_index(op.f('ix_files_file_uuid'), table_name='files')
    op.drop_index(op.f('ix_files_file_hash'), table_name='files')
    op.drop_index(op.f('ix_files_file_extension'), table_name='files')
    op.drop_index(op.f('ix_files_created_at'), table_name='files')
    op.drop_table('files')
    
    # 파일 태그 테이블 삭제
    op.drop_index(op.f('ix_file_tags_tag_name'), table_name='file_tags')
    op.drop_table('file_tags')
    
    # 파일 확장자 테이블 삭제
    op.drop_index(op.f('ix_file_extensions_extension'), table_name='file_extensions')
    op.drop_table('file_extensions')
    
    # 파일 카테고리 테이블 삭제
    op.drop_table('file_categories')
    
    # ### end Alembic commands ### 