"""Performance optimization and index tuning

Revision ID: 002
Revises: 001
Create Date: 2025-07-28 01:44:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "002"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 복합 인덱스 생성
    # 파일 조회 성능 최적화
    op.create_index(
        "ix_files_category_deleted_created",
        "files",
        ["file_category_id", "is_deleted", "created_at"],
    )

    # 파일 검색 성능 최적화
    op.create_index(
        "ix_files_extension_size_created",
        "files",
        ["file_extension", "file_size", "created_at"],
    )

    # 파일 해시 검색 최적화
    op.create_index("ix_files_hash_deleted", "files", ["file_hash", "is_deleted"])

    # 파일 조회 로그 성능 최적화
    op.create_index(
        "ix_file_views_file_type_created",
        "file_views",
        ["file_id", "view_type", "created_at"],
    )

    # 파일 다운로드 로그 성능 최적화
    op.create_index(
        "ix_file_downloads_file_method_created",
        "file_downloads",
        ["file_id", "download_method", "created_at"],
    )

    # 파일 업로드 로그 성능 최적화
    op.create_index(
        "ix_file_uploads_file_status_created",
        "file_uploads",
        ["file_id", "upload_status", "created_at"],
    )

    # 태그 검색 성능 최적화
    op.create_index("ix_file_tags_active_name", "file_tags", ["is_active", "tag_name"])

    # 파일-태그 관계 검색 최적화
    op.create_index(
        "ix_file_tag_relations_file_tag", "file_tag_relations", ["file_id", "tag_id"]
    )

    # 시스템 설정 검색 최적화
    op.create_index(
        "ix_system_settings_public_key", "system_settings", ["is_public", "setting_key"]
    )

    # 확장자 검색 성능 최적화
    op.create_index(
        "ix_file_extensions_allowed_extension",
        "file_extensions",
        ["is_allowed", "extension"],
    )

    # 카테고리 검색 성능 최적화
    op.create_index(
        "ix_file_categories_active_name", "file_categories", ["is_active", "name"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 복합 인덱스 삭제
    op.drop_index("ix_file_categories_active_name", table_name="file_categories")
    op.drop_index("ix_file_extensions_allowed_extension", table_name="file_extensions")
    op.drop_index("ix_system_settings_public_key", table_name="system_settings")
    op.drop_index("ix_file_tag_relations_file_tag", table_name="file_tag_relations")
    op.drop_index("ix_file_tags_active_name", table_name="file_tags")
    op.drop_index("ix_file_uploads_file_status_created", table_name="file_uploads")
    op.drop_index("ix_file_downloads_file_method_created", table_name="file_downloads")
    op.drop_index("ix_file_views_file_type_created", table_name="file_views")
    op.drop_index("ix_files_hash_deleted", table_name="files")
    op.drop_index("ix_files_extension_size_created", table_name="files")
    op.drop_index("ix_files_category_deleted_created", table_name="files")

    # ### end Alembic commands ###
