"""Advanced performance optimization and query tuning

Revision ID: 003
Revises: 002
Create Date: 2025-07-28 01:52:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 파일 검색 최적화를 위한 추가 복합 인덱스
    op.create_index(
        "ix_files_public_deleted_created",
        "files",
        ["is_public", "is_deleted", "created_at"],
    )

    # 파일 크기 기반 검색 최적화
    op.create_index(
        "ix_files_size_extension_created",
        "files",
        ["file_size", "file_extension", "created_at"],
    )

    # MIME 타입 기반 검색 최적화
    op.create_index(
        "ix_files_mime_deleted_created",
        "files",
        ["mime_type", "is_deleted", "created_at"],
    )

    # 카테고리별 파일 검색 최적화
    op.create_index(
        "ix_files_category_public_deleted",
        "files",
        ["file_category_id", "is_public", "is_deleted"],
    )

    # 파일 조회 통계 최적화
    op.create_index("ix_file_views_created_at", "file_views", ["created_at"])

    # 파일 다운로드 통계 최적화
    op.create_index("ix_file_downloads_created_at", "file_downloads", ["created_at"])

    # 파일 업로드 통계 최적화
    op.create_index("ix_file_uploads_created_at", "file_uploads", ["created_at"])

    # 태그 검색 성능 최적화 (태그명 기반)
    op.create_index("ix_file_tags_name_active", "file_tags", ["tag_name", "is_active"])

    # 파일-태그 관계 검색 최적화 (역방향)
    op.create_index(
        "ix_file_tag_relations_tag_file", "file_tag_relations", ["tag_id", "file_id"]
    )

    # 확장자별 파일 검색 최적화
    op.create_index(
        "ix_file_extensions_extension_allowed",
        "file_extensions",
        ["extension", "is_allowed"],
    )

    # 카테고리별 파일 검색 최적화
    op.create_index(
        "ix_file_categories_name_active", "file_categories", ["name", "is_active"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 추가 복합 인덱스 삭제
    op.drop_index("ix_file_categories_name_active", table_name="file_categories")
    op.drop_index("ix_file_extensions_extension_allowed", table_name="file_extensions")
    op.drop_index("ix_file_tag_relations_tag_file", table_name="file_tag_relations")
    op.drop_index("ix_file_tags_name_active", table_name="file_tags")
    op.drop_index("ix_file_uploads_created_at", table_name="file_uploads")
    op.drop_index("ix_file_downloads_created_at", table_name="file_downloads")
    op.drop_index("ix_file_views_created_at", table_name="file_views")
    op.drop_index("ix_files_category_public_deleted", table_name="files")
    op.drop_index("ix_files_mime_deleted_created", table_name="files")
    op.drop_index("ix_files_size_extension_created", table_name="files")
    op.drop_index("ix_files_public_deleted_created", table_name="files")

    # ### end Alembic commands ###
